#!/bin/sh
dir=$(mktemp -d)

cleanup () {
  rm -rf "$dir"
  }
trap cleanup EXIT

# install rust
./rust
# uncomment when using fedora
# sudo dnf install cmake freetype-devel fontconfig-devel libxcb-devel libxkbcommon-devel g++
# uncomment when using ubuntu/debian
sudo apt install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3


url="https://github.com/alacritty/alacritty.git"
cd $dir
git clone "$url"
cd $dir/alacritty

cargo build --release --no-default-features --features=wayland

# The -p option of mkdir is POSIX compliant; these checks avoid creating
# directories unnecessarily.
[ ! -d ~/.local ] && mkdir ~/.local
[ ! -d ~/.local/bin ] && mkdir ~/.local/bin

cp target/release/alacritty ~/.local/bin
sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
sudo desktop-file-install extra/linux/Alacritty.desktop
sudo update-desktop-database

# Theme
[ ! -d "$HOME/.config/alacritty" ] && mkdir "$HOME/.config/alacritty"
[ ! -d "$HOME/.config/alacritty/themes" ] && mkdir "$HOME/.config/alacritty/themes"

git clone https://github.com/alacritty/alacritty-theme "$HOME/.config"/alacritty/themes
