#!/bin/sh

dir=$(mktemp -d)

cleanup () {
rm -rf "$dir"
}
trap cleanup EXIT

cd $dir

curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
sudo rm -rf /opt/nvim
sudo tar -C /opt -xzf nvim-linux64.tar.gz
