#!/bin/sh
if [ -z "$(which cargo)" ]; then
    dir=$(mktemp -d)

    cleanup () {
    rm -rf "$dir"
    }
    trap cleanup EXIT

    cd $dir
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o install.sh
    chmod +x install.sh
    ./install.sh -q -y
    source "$HOME/.cargo/env"
    rustup override set stable
    rustup update stable
    cargo install eza
fi
