#!/bin/sh
url_vds="https://github.com/mikefarah/yq/releases/download/3.4.0/yq_linux_amd64"
url="https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64"
dir=$(mktemp -d)

cleanup () {
  rm -rf "$dir"
  }
trap cleanup EXIT

curl -L "$url_vds"  -o "$dir/yq"
chmod +x "$dir/yq"
curl -L "$url"  -o "$dir/yq4"
chmod +x "$dir/yq4"

cp "$dir/yq" ~/.local/bin
cp "$dir/yq4" ~/.local/bin
