import = ["~/.config/alacritty/themes/google.toml"]

[cursor]
style = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = true

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.90
decorations = "none"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 7
y = 0

[font.normal]
family = "UbuntuMono Nerd Font"

[font]
size = 14

[selection]
save_to_clipboard = true

