import = ["~/.config/alacritty/themes/google.toml"]

[cursor]
style = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = true

[shell]
program = "/usr/bin/tmux"

[window]
opacity = 0.9
decorations = "buttonless"

[window.dimensions]
columns = 120
lines = 35

[window.padding]
x = 10
y = 5

[font]
size = 14

[font.normal]
family = "UbuntuMono Nerd Font"

[selection]
save_to_clipboard = true

# Optional performance tuning
[scrolling]
history = 10000
multiplier = 3

[env]
TERM = "xterm-256color"
