#!/bin/sh
if ! type tmux >/dev/null 2>&1; then
  echo "TMUX isn't installed. Skipping."
  exit 1
fi
[ ! -d "$HOME/.tmux/" ] && mkdir $HOME/.tmux/
[ ! -d "$HOME/.tmux/plugins" ] && mkdir $HOME/.tmux/plugins
[ ! -d "$HOME/.tmux/plugins/tpm" ] && mkdir $HOME/.tmux/plugins/tpm
[ ! -d "$HOME/.tmux/plugins/kube-tmux" ] && mkdir $HOME/.tmux/plugins/kube-tmux


git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
git clone https://github.com/jonmosco/kube-tmux.git $HOME/.tmux/plugins/kube-tmux

ln -sf "$PWD/tmux.conf" "$HOME/.tmux.conf"

